/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef ROSEN_RENDER_SERVICE_BASE_TRANSACTION_RS_IRENDER_SERVICE_CONNECTION_INTERFACE_CODE_H
#define ROSEN_RENDER_SERVICE_BASE_TRANSACTION_RS_IRENDER_SERVICE_CONNECTION_INTERFACE_CODE_H

#include "ipc_security/rs_ipc_interface_code_underlying_type.h"

namespace OHOS {
namespace Rosen {

//Each command HAVE TO have UNIQUE ID in ALL HISTORY
//If a command is not used and you want to delete it, just COMMENT it
enum class RSIRenderServiceConnectionInterfaceCode : CodeUnderlyingType {
    COMMIT_TRANSACTION = 0,
    GET_UNI_RENDER_ENABLED = 1,
    CREATE_NODE = 2,
    CREATE_NODE_AND_SURFACE = 3,
    SET_FOCUS_APP_INFO = 4,
    GET_DEFAULT_SCREEN_ID = 5,
    GET_ACTIVE_SCREEN_ID = 6,
    GET_ALL_SCREEN_IDS = 7,
    CREATE_VIRTUAL_SCREEN = 8,
    SET_VIRTUAL_SCREEN_RESOLUTION = 9,
    SET_VIRTUAL_SCREEN_SURFACE = 10,
    SET_VIRTUAL_SCREEN_BLACKLIST = 11,
    ADD_VIRTUAL_SCREEN_BLACKLIST = 12,
    REMOVE_VIRTUAL_SCREEN_BLACKLIST = 13,
    SET_VIRTUAL_SCREEN_SECURITY_EXEMPTION_LIST = 14,
    SET_SCREEN_SECURITY_MASK = 15,
    SET_MIRROR_SCREEN_VISIBLE_RECT = 16,
    SET_CAST_SCREEN_ENABLE_SKIP_WINDOW = 17,
#ifdef OHOS_BUILD_ENABLE_MAGICCURSOR
    SET_POINTER_COLOR_INVERSION_CONFIG = 18,
    SET_POINTER_COLOR_INVERSION_ENABLED = 19,
    REGISTER_POINTER_LUMINANCE_CALLBACK = 20,
    UNREGISTER_POINTER_LUMINANCE_CALLBACK = 21,
#endif
    REMOVE_VIRTUAL_SCREEN = 22,
    SET_SCREEN_CHANGE_CALLBACK = 23,
    SET_SCREEN_ACTIVE_MODE = 24,
    SET_SCREEN_REFRESH_RATE = 25,
    SET_REFRESH_RATE_MODE = 26,
    SYNC_FRAME_RATE_RANGE = 27,
    UNREGISTER_FRAME_RATE_LINKER = 28,
    GET_SCREEN_CURRENT_REFRESH_RATE = 29,
    GET_CURRENT_REFRESH_RATE_MODE = 30,
    GET_SCREEN_SUPPORTED_REFRESH_RATES = 31,
    GET_SHOW_REFRESH_RATE_ENABLED = 32,
    SET_SHOW_REFRESH_RATE_ENABLED = 33,
    GET_REFRESH_INFO = 34,
    MARK_POWER_OFF_NEED_PROCESS_ONE_FRAME = 35,
    DISABLE_RENDER_CONTROL_SCREEN = 36,
    SET_SCREEN_POWER_STATUS = 37,
    SET_SCREEN_BACK_LIGHT = 38,
    TAKE_SURFACE_CAPTURE = 39,
    SET_WINDOW_FREEZE_IMMEDIATELY = 40,
    SET_POINTER_POSITION = 41,
    GET_SCREEN_ACTIVE_MODE = 42,
    GET_SCREEN_SUPPORTED_MODES = 43,
    GET_SCREEN_CAPABILITY = 44,
    GET_SCREEN_POWER_STATUS = 45,
    GET_SCREEN_BACK_LIGHT = 46,
    GET_SCREEN_DATA = 47,
    GET_VIRTUAL_SCREEN_RESOLUTION = 48,
    REGISTER_APPLICATION_AGENT = 49,
    SET_BUFFER_AVAILABLE_LISTENER = 50,
    SET_BUFFER_CLEAR_LISTENER = 51,
    GET_SCREEN_SUPPORTED_GAMUTS = 52,
    GET_SCREEN_SUPPORTED_METADATAKEYS = 53,
    GET_SCREEN_GAMUT = 54,
    SET_SCREEN_GAMUT = 55,
    SET_SCREEN_GAMUT_MAP = 56,
    SET_SCREEN_CORRECTION = 57,
    SET_VIRTUAL_MIRROR_SCREEN_CANVAS_ROTATION = 58,
    SET_VIRTUAL_MIRROR_SCREEN_SCALE_MODE = 59,
    SET_GLOBAL_DARK_COLOR_MODE = 60,
    GET_SCREEN_GAMUT_MAP = 61,
    CREATE_VSYNC_CONNECTION = 62,
    CREATE_PIXEL_MAP_FROM_SURFACE = 63,
    GET_SCREEN_HDR_CAPABILITY = 64,
    SET_PIXEL_FORMAT = 65,
    GET_PIXEL_FORMAT = 66,
    GET_SCREEN_SUPPORTED_HDR_FORMATS = 67,
    GET_SCREEN_HDR_FORMAT = 68,
    SET_SCREEN_HDR_FORMAT = 69,
    GET_SCREEN_SUPPORTED_COLORSPACES = 70,
    GET_SCREEN_COLORSPACE = 71,
    SET_SCREEN_COLORSPACE = 72,
    GET_SCREEN_TYPE = 73,
    SET_SCREEN_SKIP_FRAME_INTERVAL = 74,
    REGISTER_OCCLUSION_CHANGE_CALLBACK = 75,
    SET_APP_WINDOW_NUM = 76,
    SET_SYSTEM_ANIMATED_SCENES = 77,
    SHOW_WATERMARK = 78,
    SET_WATERMARK = 79,
    RESIZE_VIRTUAL_SCREEN = 80,
    GET_MEMORY_GRAPHIC = 81,
    GET_MEMORY_GRAPHICS = 82,
    GET_TOTAL_APP_MEM_SIZE = 83,
    REPORT_JANK_STATS = 84,
    REPORT_EVENT_RESPONSE = 85,
    REPORT_EVENT_COMPLETE = 86,
    REPORT_EVENT_JANK_FRAME = 87,
    REPORT_EVENT_GAMESTATE = 88,
    GET_BITMAP = 89,
    GET_PIXELMAP = 90,
    EXECUTE_SYNCHRONOUS_TASK = 91,
    NOTIFY_TOUCH_EVENT = 92,
    SET_HARDWARE_ENABLED = 93,
    REGISTER_SURFACE_OCCLUSION_CHANGE_CALLBACK = 94,
    UNREGISTER_SURFACE_OCCLUSION_CHANGE_CALLBACK = 95,
    REGISTER_HGM_CFG_CALLBACK = 96,
    SET_ROTATION_CACHE_ENABLED = 97,
    SET_TP_FEATURE_CONFIG = 98,
    SET_VIRTUAL_SCREEN_USING_STATUS = 99,
    REFRESH_RATE_MODE_CHANGE_CALLBACK = 100,
    SET_CURTAIN_SCREEN_USING_STATUS = 101,
    DROP_FRAME_BY_PID = 102,
    REGISTER_TYPEFACE = 103,
    UNREGISTER_TYPEFACE = 104,
    REFRESH_RATE_UPDATE_CALLBACK = 105,
    REGISTER_FRAME_RATE_LINKER_EXPECTED_FPS_CALLBACK = 106,
    GET_ACTIVE_DIRTY_REGION_INFO = 107,
    GET_GLOBAL_DIRTY_REGION_INFO = 108,
    GET_LAYER_COMPOSE_INFO = 109,
    GET_HARDWARE_COMPOSE_DISABLED_REASON_INFO = 110,
    GET_HDR_ON_DURATION = 111,
    REGISTER_UIEXTENSION_CALLBACK = 112,
    SET_VIRTUAL_SCREEN_STATUS = 113,
    SET_ANCO_FORCE_DO_DIRECT = 114,
    SET_VMA_CACHE_STATUS = 115,
    NEED_REGISTER_TYPEFACE = 116,
    CREATE_DISPLAY_NODE = 117,
    SET_FREE_MULTI_WINDOW_STATUS = 118,
    REGISTER_SURFACE_BUFFER_CALLBACK = 119,
    UNREGISTER_SURFACE_BUFFER_CALLBACK = 120,
    SET_LAYER_TOP = 121,
    SET_VIRTUAL_SCREEN_REFRESH_RATE = 122,
    SET_SCREEN_ACTIVE_RECT = 123,
    SET_HIDE_PRIVACY_CONTENT = 124,
    REPAINT_EVERYTHING = 125,
    FORCE_REFRESH_ONE_FRAME_WITH_NEXT_VSYNC = 126,
// Special invocation. Do not change it.
    NOTIFY_LIGHT_FACTOR_STATUS = 1000,
    NOTIFY_PACKAGE_EVENT = 1001,
    NOTIFY_REFRESH_RATE_EVENT = 1002,
    NOTIFY_DYNAMIC_MODE_EVENT = 1003,
    NOTIFY_SOFT_VSYNC_EVENT = 1004,
    NOTIFY_SCREEN_SWITCHED = 1005,
};
} // namespace Rosen
} // namespace OHOS

#endif // ROSEN_RENDER_SERVICE_BASE_TRANSACTION_RS_IRENDER_SERVICE_CONNECTION_INTERFACE_CODE_H
