/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This file is generated by AI.
#include <filesystem>
#include <fstream>
#include <gtest/gtest.h>

#include "font_config.h"

using namespace testing;
using namespace testing::ext;

namespace OHOS {
namespace Rosen {
namespace TextEngine {

// Test JSON configuration for font config
static const char* VALID_FONT_CONFIG_JSON = R"(
{
    "font_dir": [
        "/system/fonts",
        "/data/fonts"
    ],
    "fonts": [
        {
            "type": 0,
            "alias": "Sans",
            "family": "Noto Sans",
            "weight": 400,
            "lang": "en",
            "file": "NotoSans.ttf"
        },
        {
            "type": 1,
            "family": "Test Sans",
            "file": "TestSans.ttf"
        }
    ]
}
)";

// Minimal valid JSON with font_dir only
static const char* MINIMAL_FONT_CONFIG_JSON = R"(
{
    "font_dir": ["/system/fonts"]
}
)";

// Invalid JSON (malformed)
static const char* INVALID_JSON = R"(
{
    "font_dir": [
        "/system/fonts",
    )
}";

// Valid JSON but missing required keys
static const char* INVALID_FONT_CONFIG_JSON = R"(
{
    "invalid_key": "value"
}
)";

// Empty JSON object
static const char* EMPTY_JSON = R"(
{
}
)";

class FontConfigTest : public testing::Test {
protected:
    void SetUp() override {}
    void TearDown() override {}
};

// Helper function to create a temporary config file
std::string CreateTempConfigFile(const char* content, const std::string& suffix = ".json")
{
    std::string tempDir = "/data/local/tmp";
    std::string tempFile = tempDir + "/font_config_test" + suffix + "_XXXXXX";

    // Create unique filename
    char* templateStr = strdup(tempFile.c_str());
    int fd = mkstemp(templateStr);
    if (fd == -1) {
        free(templateStr);
        return "";
    }

    // Write content
    write(fd, content, strlen(content));
    close(fd);

    std::string result(templateStr);
    free(templateStr);
    return result;
}

/**
 * @tc.name: ParseFileWithDefaultPathTest
 * @tc.desc: test ParseFile with default path (nullptr parameter)
 * @tc.type: FUNC
 */
HWTEST_F(FontConfigTest, ParseFileWithDefaultPathTest, TestSize.Level0)
{
    FontConfigJson fontConfigJson;

    // Test with nullptr - should use default config path
    int result = fontConfigJson.ParseFile(nullptr);

    // If default config exists, should succeed; otherwise may fail
    // We mainly check that it doesn't crash
    auto info = fontConfigJson.GetFontConfigJsonInfo();
    EXPECT_EQ(result, 0);
    ASSERT_NE(info, nullptr);
}

/**
 * @tc.name: ParseFileWithValidConfigTest
 * @tc.desc: test ParseFile with valid configuration file
 * @tc.type: FUNC
 */
HWTEST_F(FontConfigTest, ParseFileWithValidConfigTest, TestSize.Level0)
{
    std::string tempFile = CreateTempConfigFile(VALID_FONT_CONFIG_JSON);
    ASSERT_FALSE(tempFile.empty()) << "Failed to create temp config file";

    FontConfigJson fontConfigJson;
    int result = fontConfigJson.ParseFile(tempFile.c_str());

    EXPECT_EQ(result, 0);

    auto info = fontConfigJson.GetFontConfigJsonInfo();
    ASSERT_NE(info, nullptr);
    EXPECT_EQ(info->fontDirSet.size(), 2);
    EXPECT_FALSE(info->genericSet.empty());

    // Clean up
    unlink(tempFile.c_str());
}

/**
 * @tc.name: ParseFileWithMinimalConfigTest
 * @tc.desc: test ParseFile with minimal valid configuration
 * @tc.type: FUNC
 */
HWTEST_F(FontConfigTest, ParseFileWithMinimalConfigTest, TestSize.Level0)
{
    std::string tempFile = CreateTempConfigFile(MINIMAL_FONT_CONFIG_JSON);
    ASSERT_FALSE(tempFile.empty()) << "Failed to create temp config file";

    FontConfigJson fontConfigJson;
    int result = fontConfigJson.ParseFile(tempFile.c_str());

    EXPECT_EQ(result, 0);

    auto info = fontConfigJson.GetFontConfigJsonInfo();
    ASSERT_NE(info, nullptr);
    EXPECT_EQ(info->fontDirSet.size(), 1);
    EXPECT_EQ(info->fontDirSet[0], "/system/fonts");

    // Clean up
    unlink(tempFile.c_str());
}

/**
 * @tc.name: ParseFileWithInvalidJsonTest
 * @tc.desc: test ParseFile with malformed JSON
 * @tc.type: FUNC
 */
HWTEST_F(FontConfigTest, ParseFileWithInvalidJsonTest, TestSize.Level0)
{
    std::string tempFile = CreateTempConfigFile(INVALID_JSON);
    ASSERT_FALSE(tempFile.empty()) << "Failed to create temp config file";

    FontConfigJson fontConfigJson;
    int result = fontConfigJson.ParseFile(tempFile.c_str());

    // Should fail due to malformed JSON
    EXPECT_NE(result, 0);

    // Clean up
    unlink(tempFile.c_str());
}

/**
 * @tc.name: ParseFileWithEmptyJsonTest
 * @tc.desc: test ParseFile with empty JSON object
 * @tc.type: FUNC
 */
HWTEST_F(FontConfigTest, ParseFileWithEmptyJsonTest, TestSize.Level0)
{
    std::string tempFile = CreateTempConfigFile(EMPTY_JSON);
    ASSERT_FALSE(tempFile.empty()) << "Failed to create temp config file";

    FontConfigJson fontConfigJson;
    int result = fontConfigJson.ParseFile(tempFile.c_str());

    // Empty JSON should succeed (no fonts, but valid JSON)
    EXPECT_EQ(result, 0);

    auto info = fontConfigJson.GetFontConfigJsonInfo();
    ASSERT_NE(info, nullptr);
    EXPECT_TRUE(info->fontDirSet.empty());
    EXPECT_TRUE(info->genericSet.empty());

    // Clean up
    unlink(tempFile.c_str());
}

/**
 * @tc.name: ParseFileWithNonExistentPathTest
 * @tc.desc: test ParseFile with non-existent file path
 * @tc.type: FUNC
 */
HWTEST_F(FontConfigTest, ParseFileWithNonExistentPathTest, TestSize.Level0)
{
    FontConfigJson fontConfigJson;
    int result = fontConfigJson.ParseFile("/non/existent/path/fontconfig.json");

    // Should fail with non-existent file
    EXPECT_NE(result, 0);
}

/**
 * @tc.name: ParseFileMultipleTimesTest
 * @tc.desc: test calling ParseFile multiple times
 * @tc.type: FUNC
 */
HWTEST_F(FontConfigTest, ParseFileMultipleTimesTest, TestSize.Level0)
{
    std::string tempFile1 = CreateTempConfigFile(VALID_FONT_CONFIG_JSON, "_1.json");
    ASSERT_FALSE(tempFile1.empty()) << "Failed to create first temp config file";

    std::string tempFile2 = CreateTempConfigFile(MINIMAL_FONT_CONFIG_JSON, "_2.json");
    ASSERT_FALSE(tempFile2.empty()) << "Failed to create second temp config file";

    FontConfigJson fontConfigJson;

    // First parse
    int result1 = fontConfigJson.ParseFile(tempFile1.c_str());
    EXPECT_EQ(result1, 0);
    auto info1 = fontConfigJson.GetFontConfigJsonInfo();
    ASSERT_NE(info1, nullptr);
    size_t firstDirSize = info1->fontDirSet.size();

    // Second parse - should overwrite
    int result2 = fontConfigJson.ParseFile(tempFile2.c_str());
    EXPECT_EQ(result2, 0);
    auto info2 = fontConfigJson.GetFontConfigJsonInfo();
    ASSERT_NE(info2, nullptr);
    EXPECT_EQ(info2->fontDirSet.size(), 1);
    EXPECT_NE(info2->fontDirSet.size(), firstDirSize);

    // Clean up
    unlink(tempFile1.c_str());
    unlink(tempFile2.c_str());
}

/**
 * @tc.name: ParseFileWithGenericFontTest
 * @tc.desc: test ParseFile with generic font type
 * @tc.type: FUNC
 */
HWTEST_F(FontConfigTest, ParseFileWithGenericFontTest, TestSize.Level0)
{
    std::string tempFile = CreateTempConfigFile(VALID_FONT_CONFIG_JSON);
    ASSERT_FALSE(tempFile.empty()) << "Failed to create temp config file";

    FontConfigJson fontConfigJson;
    int result = fontConfigJson.ParseFile(tempFile.c_str());

    EXPECT_EQ(result, 0);

    auto info = fontConfigJson.GetFontConfigJsonInfo();
    ASSERT_NE(info, nullptr);

    // Check generic set contains the generic font (type = 0)
    ASSERT_FALSE(info->genericSet.empty()) << "Generic set should not be empty";
    EXPECT_FALSE(info->genericSet[0].aliasSet.empty());
    EXPECT_EQ(info->genericSet[0].familyName, "Noto Sans");

    // Check adjustSet is set (compatible with old version)
    EXPECT_FALSE(info->genericSet[0].adjustSet.empty());

    // Clean up
    unlink(tempFile.c_str());
}

/**
 * @tc.name: ParseFileFallbackGroupTest
 * @tc.desc: test ParseFile creates default fallback group
 * @tc.type: FUNC
 */
HWTEST_F(FontConfigTest, ParseFileFallbackGroupTest, TestSize.Level0)
{
    std::string tempFile = CreateTempConfigFile(MINIMAL_FONT_CONFIG_JSON);
    ASSERT_FALSE(tempFile.empty()) << "Failed to create temp config file";

    FontConfigJson fontConfigJson;
    int result = fontConfigJson.ParseFile(tempFile.c_str());

    EXPECT_EQ(result, 0);

    auto info = fontConfigJson.GetFontConfigJsonInfo();
    ASSERT_NE(info, nullptr);

    // Should have at least one fallback group with empty name
    EXPECT_FALSE(info->fallbackGroupSet.empty());
    EXPECT_TRUE(info->fallbackGroupSet[0].groupName.empty());

    // Clean up
    unlink(tempFile.c_str());
}

/**
 * @tc.name: ParseFileWithFallbackFontTest
 * @tc.desc: test ParseFile with fallback font type
 * @tc.type: FUNC
 */
HWTEST_F(FontConfigTest, ParseFileWithFallbackFontTest, TestSize.Level0)
{
    std::string tempFile = CreateTempConfigFile(VALID_FONT_CONFIG_JSON);
    ASSERT_FALSE(tempFile.empty()) << "Failed to create temp config file";

    FontConfigJson fontConfigJson;
    int result = fontConfigJson.ParseFile(tempFile.c_str());

    EXPECT_EQ(result, 0);

    auto info = fontConfigJson.GetFontConfigJsonInfo();
    ASSERT_NE(info, nullptr);

    // Check fallback group contains the fallback font (type = 1)
    ASSERT_FALSE(info->fallbackGroupSet.empty()) << "Fallback group set should not be empty";
    ASSERT_FALSE(info->fallbackGroupSet[0].fallbackInfoSet.empty()) << "Fallback info set should not be empty";
    const auto& fallbackInfo = info->fallbackGroupSet[0].fallbackInfoSet[0];
    EXPECT_EQ(fallbackInfo.familyName, "Test Sans");
    EXPECT_EQ(fallbackInfo.path, "TestSans.ttf");

    // Clean up
    unlink(tempFile.c_str());
}

/**
 * @tc.name: ParseFileIndexMapTest
 * @tc.desc: test ParseFile initializes index map correctly
 * @tc.type: FUNC
 */
HWTEST_F(FontConfigTest, ParseFileIndexMapTest, TestSize.Level0)
{
    std::string tempFile = CreateTempConfigFile(VALID_FONT_CONFIG_JSON);
    ASSERT_FALSE(tempFile.empty()) << "Failed to create temp config file";

    FontConfigJson fontConfigJson;
    int result = fontConfigJson.ParseFile(tempFile.c_str());

    EXPECT_EQ(result, 0);

    // The indexMap is a private member, but we can verify its effect
    // by checking that genericSet was populated correctly
    auto info = fontConfigJson.GetFontConfigJsonInfo();
    ASSERT_NE(info, nullptr);

    // If generic font was added, indexMap should have been used
    ASSERT_FALSE(info->genericSet.empty()) << "Generic set should not be empty";
    EXPECT_EQ(info->genericSet[0].familyName, "Noto Sans");

    // Clean up
    unlink(tempFile.c_str());
}

/**
 * @tc.name: ParseFileDumpTest
 * @tc.desc: test ParseFile and Dump function
 * @tc.type: FUNC
 */
HWTEST_F(FontConfigTest, ParseFileDumpTest, TestSize.Level0)
{
    std::string tempFile = CreateTempConfigFile(VALID_FONT_CONFIG_JSON);
    ASSERT_FALSE(tempFile.empty()) << "Failed to create temp config file";

    FontConfigJson fontConfigJson;
    int result = fontConfigJson.ParseFile(tempFile.c_str());

    EXPECT_EQ(result, 0);

    // Dump should not crash
    fontConfigJson.Dump();

    // Clean up
    unlink(tempFile.c_str());
}

/**
 * @tc.name: ParseFileWithEmptyPathTest
 * @tc.desc: test ParseFile with empty string path
 * @tc.type: FUNC
 */
HWTEST_F(FontConfigTest, ParseFileWithEmptyPathTest, TestSize.Level0)
{
    FontConfigJson fontConfigJson;
    int result = fontConfigJson.ParseFile("");

    // Empty path should fail or use default (depending on implementation)
    // The important thing is it shouldn't crash
    EXPECT_EQ(result, 1);
}

} // namespace TextEngine
} // namespace Rosen
} // namespace OHOS
