/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef RENDER_SERVICE_BASE_PLATFORM_OHOS_TRANSACTION_RS_ICLIENT_TO_RENDER_CONNECTION_IPC_INTERFACE_CODE_H
#define RENDER_SERVICE_BASE_PLATFORM_OHOS_TRANSACTION_RS_ICLIENT_TO_RENDER_CONNECTION_IPC_INTERFACE_CODE_H

#include "ipc_security/rs_ipc_interface_code_underlying_type.h"

namespace OHOS {
namespace Rosen {

//Each command HAVE TO have UNIQUE ID in ALL HISTORY
//If a command is not used and you want to delete it,
//just COMMENT it - and never use this value anymore
enum class RSIClientToRenderConnectionInterfaceCode : CodeUnderlyingType {
    COMMIT_TRANSACTION = 0x000000,
    CREATE_NODE = 0x000002,
    CREATE_NODE_AND_SURFACE = 0x000003,
    SET_FOCUS_APP_INFO = 0x000004,
    SET_APP_WINDOW_NUM = 0x000016,
    TAKE_SURFACE_CAPTURE = 0x00000D,
    SET_WINDOW_FREEZE_IMMEDIATELY = 0x00000E,
    SET_POINTER_POSITION = 0x00000F,
    REGISTER_APPLICATION_AGENT = 0x000011,
    SET_BUFFER_AVAILABLE_LISTENER = 0x000012,
    SET_BUFFER_CLEAR_LISTENER = 0x000013,
    SET_SYSTEM_ANIMATED_SCENES = 0x000017,
    DROP_FRAME_BY_PID = 0x00001C,
    SET_ANCO_FORCE_DO_DIRECT = 0x000021,
    CREATE_DISPLAY_NODE = 0x000023,
    REGISTER_SURFACE_BUFFER_CALLBACK = 0x000025,
    UNREGISTER_SURFACE_BUFFER_CALLBACK = 0x000026,
    SET_HIDE_PRIVACY_CONTENT = 0x000029,
    FORCE_REFRESH_ONE_FRAME_WITH_NEXT_VSYNC = 0x00002B,
    SET_WINDOW_CONTAINER = 0x00002C,
    TAKE_SELF_SURFACE_CAPTURE = 0x000030,
    TAKE_SURFACE_CAPTURE_SOLO = 0x000032,
    TAKE_UI_CAPTURE_IN_RANGE = 0x000035,
    SET_LAYER_TOP_FOR_HARDWARE_COMPOSER = 0x00003B,
    TAKE_SURFACE_CAPTURE_WITH_ALL_WINDOWS = 0x00003D,
    FREEZE_SCREEN = 0x000040,
    SET_GLOBAL_DARK_COLOR_MODE = 0x007005,

    GET_BITMAP = 0x00800C,
    GET_PIXELMAP = 0x00800D,

    GET_SCREEN_HDR_STATUS = 0x00800E,
    GET_BRIGHTNESS_INFO = 0x008010,
#if defined(ROSEN_OHOS) && defined(RS_ENABLE_VK)
    REGISTER_CANVAS_CALLBACK = 0x008011,
    SUBMIT_CANVAS_PRE_ALLOCATED_BUFFER = 0x008012,
#endif
    REGISTER_TRANSACTION_DATA_CALLBACK = 0x009002,
    SET_SURFACE_WATERMARK = 0X009003,
    CLEAR_SURFACE_WATERMARK_FOR_NODES = 0X009004,
    CLEAR_SURFACE_WATERMARK = 0X009005,

    EXECUTE_SYNCHRONOUS_TASK = 0x00C000,
    SET_HARDWARE_ENABLED = 0x00C002,
    GET_HIGH_CONTRAST_TEXT_STATE = 0x012000,

    CLEAR_UIFIRST_CACHE = 0X15000,
};
} // namespace Rosen
} // namespace OHOS

#endif // RENDER_SERVICE_BASE_PLATFORM_OHOS_TRANSACTION_RS_IRENDER_SERVICE_CONNECTION_IPC_INTERFACE_CODE_H
