/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE  0-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef RENDER_SERVICE_MAIN_RENDER_PROCESS_TRANSACTION_ZIDL_RS_ISERVICE_TO_RENDER_CONNECTION_IPC_INTERFACE_CODE_H
#define RENDER_SERVICE_MAIN_RENDER_PROCESS_TRANSACTION_ZIDL_RS_ISERVICE_TO_RENDER_CONNECTION_IPC_INTERFACE_CODE_H

#include "ipc_security/rs_ipc_interface_code_underlying_type.h"

namespace OHOS {
namespace Rosen {

enum class RSIServiceToRenderConnectionInterfaceCode : CodeUnderlyingType {
    DFX_DUMP = 4,
    NOTIFY_PACKAGE_EVENT = 5,
    GET_MEMORY_GRAPHIC = 6,
    HGM_FORCE_UPDATE_TASK = 7,
    REPAINT_EVERYTHING = 8,
    SET_BEHIND_WINDOW_FILTER_ENABLED = 11,
    GET_BEHIND_WINDOW_FILTER_ENABLED = 12,
    GET_MEMORY_GRAPHICS = 13,
    GET_TOTAL_APP_MEM_SIZE = 14,
    GET_PIXELMAP_BY_PROCESSID = 15,
    SET_WATERMARK = 16,
    SHOW_WATERMARK = 17,
    GET_REALTIME_REFRESH_RATE = 18,
    SET_SHOW_REFRESH_RATE_ENABLED = 19,
    GET_SHOW_REFRESH_RATE_ENABLED = 20,
    AVCODEC_VIDEO_START = 22,
    AVCODEC_VIDEO_STOP = 23,
    AVCODEC_VIDEO_GET = 24,
    AVCODEC_VIDEO_GET_RECENT = 25,
#ifdef RS_ENABLE_OVERLAY_DISPLAY
    SET_OVERLAY_DISPLAY_MODE = 27,
#endif
    GET_ACTIVE_DIRTY_REGION_INFO = 28,
    GET_GLOBAL_DIRTY_REGION_INFO = 29,
    GET_LAYER_COMPOSE_INFO = 30,
    GET_HARDWARE_COMPOSE_DISABLED_REASON_INFO = 31,
    GET_HDR_ON_DURATION = 32,
    NOTIFY_SCREEN_REFRESH = 33,
    SET_OPTIMIZE_CANVAS_DIRTY_ENABLED_PIDLIST = 34,
    REPORT_EVENT_GAMESTATE = 50,
    GET_SURFACE_ROOT_NODE = 51,
    SET_FREE_MULTI_WINDOW_STATUS = 0x000024,
    REPORT_JANK_STATS = 0x000025,
    REPORT_EVENT_RESPONSE = 0x000026,
    REPORT_EVENT_COMPLETE = 0x000027,
    REPORT_EVENT_JANK_FRAME = 0x000028,
    REPORT_RS_SCENE_JANK_START = 0x000029,
    REPORT_RS_SCENE_JANK_END = 0x00002A,
    FORCE_REFRESH_ONE_FRAME_WITH_NEXT_VSYNC = 0x00002B,
    SET_GPU_CRC_DIRTY_ENABLED_PIDLIST = 0x00003E,
    REGISTER_SELF_DRAWING_NODE_RECT_CHANGE_CALLBACK = 0x00E010,
    UNREGISTER_SELF_DRAWING_NODE_RECT_CHANGE_CALLBACK = 0x00E011,
    REGISTER_TYPEFACE = 0x00E000,
    UNREGISTER_TYPEFACE = 0x00E001,
    NEED_REGISTER_TYPEFACE = 0x00E002,
    HANDLE_HWC_EVENT = 0x00E003,
    SET_BRIGHTNESS_INFO_CHANGE_CALLBACK = 0x00E007,
    SET_FORCE_REFRESH = 0x00F000,
    CREATE_PIXEL_MAP_FROM_SURFACE = 0X00F001,
    SET_LAYER_TOP = 0X00F002,
    REGISTER_UIEXTENSION_CALLBACK = 0X00F003,
    SET_VMA_CACHE_STATUS = 0X00F005,
    GET_PID_GPU_MEMORY_IN_MB = 0X00F006,
    SET_COLOR_FOLLOW = 0X00F007,
    SET_CURTAIN_SCREEN_USING_STATUS = 0x00F008,
    CLEAN_RESOURCE = 0X00F010,
    SET_BACKLIGHT_LEVEL = 0x00F011,
    ON_GLOBAL_BLACKLIST_CHANGED = 0x00F012,
};

} // namespace Rosen
} // namespace OHOS

#endif // RENDER_SERVICE_MAIN_RENDER_PROCESS_TRANSACTION_ZIDL_RS_ISERVICE_TO_RENDER_CONNECTION_IPC_INTERFACE_CODE_H